herramienta_sorteo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('subir_csv/', views.subir_csv, name='subir_csv'),
    path('resumen_de_datos/', views.resumen_de_datos, name='resumen_de_datos'),
    path('procesar_participantes_csv/', views.procesar_participantes_csv, name='procesar_participantes_csv'),
    path('participantes/', views.participantes, name='participantes'),
    path('millares/', views.millares, name='millares'),
    path('ayuda/', views.ayuda, name='ayuda'),
    path('herramientas/', views.herramientas, name='herramientas'),
    path('reiniciar_sistema/', views.reiniciar_sistema, name='reiniciar_sistema'),
    path('resetear_ganadores/', views.resetear_ganadores, name='resetear_ganadores'),
    path('realizar_sorteo/', views.realizar_sorteo, name='realizar_sorteo'),
    path('ver_sorteo/', views.ver_sorteo, name='ver_sorteo'),
    path('descargar_csv_sorteo/', views.descargar_csv_sorteo, name='descargar_csv_sorteo'),
    path('descargar_pdf_sorteo/', views.descargar_pdf_sorteo, name='descargar_pdf_sorteo'),
]

templates/secciones/aviso.html
<div class="container mx-auto py-8 w-2/3 text-rojoosasuna">
    <div class="flex justify-center">
        <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">{{ titulo }}</h1>
    </div>
    <p class="mt-2">{{ texto }}</p>
</div>

templates/secciones/contenido_millares.html
<div class="container mx-auto p-4">
    {% for millar in sorteo.millares %}
        <div class="mb-8 bg-gray-300 shadow-lg rounded-lg p-6">
            <h2 class="text-2xl text-center font-bold mb-4 osasuna-camisetas-font">{{ millar }}</h2>
            <div class="grid grid-cols-5 gap-2 mb-4">
                <!-- <div class="bg-gray-100 p-2 rounded-lg text-center">
                    <p class="text-sm font-semibold">Participantes</p>
                    <p class="text-lg">{{ millar.cuenta_participantes }}</p>
                </div> -->
                <div class="bg-gray-100 p-2 rounded-lg text-center">
                    <p class="text-sm font-semibold">Seleccionados totales</p>
                    <p class="text-lg">{{ millar.cuenta_participantes_ganadores }}</p>
                </div>
                <div class="bg-gray-100 p-2 rounded-lg text-center">
                    <p class="text-sm font-semibold">Seleccionados primera fase</p>
                    <p class="text-lg">{{ millar.cuenta_participantes_ganadores_primera_fase }}</p>
                </div>
                <div class="bg-gray-100 p-2 rounded-lg text-center">
                    <p class="text-sm font-semibold">Seleccionados segunda fase</p>
                    <p class="text-lg">{{ millar.cuenta_participantes_ganadores_segunda_fase }}</p>
                </div>
                <div class="bg-gray-100 p-2 rounded-lg text-center">
                    <p class="text-sm font-semibold">Seleccionados tercera fase</p>
                    <p class="text-lg">{{ millar.cuenta_participantes_ganadores_tercera_fase }}</p>
                </div>
                <div class="bg-gray-100 p-2 rounded-lg text-center">
                    <p class="text-sm font-semibold">Participantes no seleccionados</p>
                    <p class="text-lg">{{ millar.cuenta_participantes_no_ganadores }}</p>
                </div>
            </div>
            {% include 'secciones/tabla_participantes.html' with participantes=millar.participantes %}
        </div>
    {% endfor %}
</div>

templates/secciones/index_csvs.html
<div class="flex flex-col items-center justify-center">
    {% if total_csvs == 0 %}
            {% include 'secciones/instrucciones_1.html' %}
        {% elif total_csvs == 1 %}
            {% include 'secciones/instrucciones_2.html' %}
        {% else %}
            {% include 'secciones/instrucciones_error_varios_csvs.html' %}
    {% endif %}
    <div class="bg-gray-100 p-8 rounded-lg shadow-lg max-w-md w-full">
        <div class="text-center">
            {% if total_csvs == 0 %}
                <p class="text-red-500 text-lg font-semibold">No hay CSV</p>
                <p class="text-gray-600 mt-2">No se ha encontrado ningún archivo CSV. Por favor, suba un archivo CSV para continuar.</p>
                <div class="mt-4 flex justify-center">
                    <form id="csvForm" action="{% url 'main_app:subir_csv' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p id="fileName" class="m-2 text-gray-700 font-bold text-lg"></p>
                        <input id="csvFileInput" type="file" name="csv_file" class="hidden" required>
                        <button type="button" id="customButton" class="bg-rojoosasuna text-white font-bold py-2 px-4 rounded">
                            Seleccionar CSV
                        </button>
                        <button type="button" id="customSubmitButton" class="bg-azulosasuna text-white font-bold py-2 px-4 rounded">
                            Subir CSV
                        </button>
                        <button type="submit" class="hidden">Submit</button>
                        <p id="errorMessage" class="mt-4 text-red-500 font-bold hidden">Selecciona un archivo.</p>

                    </form>
                </div>
            {% elif total_csvs == 1 %}
                <p class="text-rojoosasuna text-lg font-semibold">Hay 1 CSV</p>
                <p class="text-gray-600 mt-2">El archivo CSV se ha cargado correctamente y está listo para su uso.</p>
                <div class="mt-4 flex justify-center">
                    <a href="{% url 'main_app:procesar_participantes_csv' %}" class="bg-azulosasuna text-white font-bold py-2 px-4 rounded">
                        Procesar CSV y generar participantes
                    </a>
                </div>

            {% else %}
                <p class="text-rojoosasuna text-lg font-semibold">Hay {{ total_csvs }} CSVs</p>
                <p class="text-gray-600 mt-2">Debería haber únicamente un archivo CSV con los participantes del sorteo. Por favor, elimina todos los CSV excepto el que va a ser utilizado para seleccionar a los participantes del sorteo.</p>
                <div class="mt-4 flex justify-center">
                    <a href="{% url 'admin:main_app_csvparticipantes_changelist' %}" class="bg-azulosasuna text-white font-bold py-2 px-4 rounded">
                        Ir a la lista de CSVs
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<script>
    document.getElementById('customButton').addEventListener('click', function() {
        document.getElementById('csvFileInput').click();
    });

    document.getElementById('customSubmitButton').addEventListener('click', function() {
        const fileInput = document.getElementById('csvFileInput');
        const errorMessage = document.getElementById('errorMessage');
        if (!fileInput.files.length) {
            errorMessage.classList.remove('hidden');
        } else {
            errorMessage.classList.add('hidden');
            document.querySelector('form').submit();
        }
    });

    document.getElementById('csvFileInput').addEventListener('change', function() {
        var fileName = document.getElementById('csvFileInput').files[0].name;
        document.getElementById('fileName').textContent = fileName;
    });
</script>

templates/secciones/index_generar_sorteo.html
<div class="flex flex-col items-center justify-center">
    {% include 'secciones/instrucciones_3.html' %}
    <div class="mt-6">
        <button id="launch-button" class="bg-azulosasuna text-white font-bold py-6 px-12 rounded-full shadow-lg text-3xl transition duration-300 ease-in-out transform hover:scale-105">
            Realizar sorteo
        </button>
    </div>
    <div id="loading-popup" class="hidden fixed inset-0 bg-gray-800 bg-opacity-75 flex items-center justify-center">
        <div class="bg-white p-12 rounded-lg shadow-2xl text-center max-w-3xl">
            <div id="loading-text" class="text-4xl font-bold mb-8 text-azulosasuna osasuna-camisetas-font">Realizando sorteo</div>
            <div id="loading-items" class="text-2xl text-gray-800"></div>
        </div>
    </div>
</div>

<input type="hidden" id="csrf-token" value="{{ csrf_token }}">

<script>
    function getCsrfToken() {
        return document.getElementById('csrf-token').value;
    }

    function showLoadingPopup(totalMillares, totalFases, callback) {
        const loadingPopup = document.getElementById('loading-popup');
        const loadingText = document.getElementById('loading-text');
        const loadingItems = document.getElementById('loading-items');

        loadingPopup.classList.remove('hidden');
        let millar = 1;
        let fase = 1;

        function getRandomDelay(min, max) {
            return Math.floor(Math.random() * (max - min + 1)) + min;
        }

        function showNextItem() {
            if (fase <= totalFases) {
                loadingItems.textContent = `Fase ${fase}, millar ${millar}`;
                millar++;
                if (millar > totalMillares) {
                    millar = 1;
                    fase++;
                }
                setTimeout(showNextItem, getRandomDelay(100, 200));
            } else {
                loadingText.textContent = '¡Sorteo completado!';
                setTimeout(callback, 3000);
            }
        }

        showNextItem();
    }

    document.getElementById('launch-button').addEventListener('click', function() {
        const totalMillares = {{ total_millares }};
        const totalFases = 3;

        showLoadingPopup(totalMillares, totalFases, function() {
            const csrfToken = getCsrfToken();
            fetch("{% url 'main_app:realizar_sorteo' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                }
            })
            .then(response => {
                if (response.redirected) {
                    window.location.href = response.url;
                } else {
                    return response.json();
                }
            })
            .then(data => {
                if (data && data.redirect_url) {
                    window.location.href = data.redirect_url;
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
        });
    });
</script>

templates/secciones/index_presorteo.html
{% if total_participantes == 0 %}
    {% include 'secciones/index_csvs.html' %}
{% else %}
    <div class="flex flex-col items-center justify-center">
        {% include 'secciones/instrucciones_tras_cargado_datos.html' %}
    </div>
{% endif %}

templates/secciones/index_resultado_sorteo.html
<div class="flex flex-col items-center justify-center">
    {% include 'secciones/instrucciones_4.html' %}
    <div class="bg-gray-100 shadow-lg rounded-lg p-8 max-w-lg text-center">
        <h1 class="text-4xl font-bold mb-4 osasuna-camisetas-font">Sorteo completado</h1>
        <a href="{% url 'main_app:descargar_csv_sorteo' %}" class="inline-block bg-rojoosasuna text-white font-bold py-2 px-4 rounded">
            Descargar CSV
        </a>
        <a href="{% url 'main_app:descargar_pdf_sorteo' %}" class="inline-block bg-azulosasuna text-white font-bold py-2 px-4 rounded">
            Descargar PDF
        </a>
    </div>
</div>

templates/secciones/instrucciones_1.html
<div class="container mx-auto py-8 w-2/3">
    <div class="flex justify-center">
        <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">Parte 1 del sorteo</h1>
    </div>
    <p class="text-gray-600 mt-2">Para comenzar con el sorteo, se necesita la lista de participantes. Dicha lista ha de ser provista en formato CSV con el diseño acordado de 4 columnas: Millar, posición en millar, número de socio y nombre+apellidos.</p>
    <p class="text-gray-600 mt-2">En la sección inferior se puede subir el archivo que contiene los participantes seleccionando el botón Seleccionar CSV. Ello abrirá una ventana de selección de archivos, donde se seleccionará el archivo previamente preparado. Una vez hecho, pulsar el botón de Subir CSV.</p>
</div>

templates/secciones/instrucciones_2.html
<div class="container mx-auto py-8 w-2/3">
    <div class="flex justify-center">
        <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">Parte 2 del sorteo</h1>
    </div>
    <p class="text-gray-600 mt-2">El archivo está correctamente almacenado en el sistema, pero no se ha procesado y aún no hay participantes en el sistema. En la sección inferior se puede pulsar el botón </p>
    <p class="text-gray-600 mt-2">En la sección inferior se puede pulsar el botón "Procesar CSV y generar participantes" para analizar el archivo y obtener los participantes del sorteo.</p>
</div>

templates/secciones/instrucciones_3.html
<div class="container mx-auto py-8 w-2/3">
    <div class="flex justify-center">
        <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">Parte 3 del sorteo</h1>
    </div>
    <p class="text-gray-600 mt-2">El sistema ha procesado el CSV y ha generado los participantes{% if total_participantes %}, habiendo un total de {{ total_participantes }} participantes{% endif %}. Pueden comprobarse los datos en las secciones apropiadas en el menú lateral.</p>
    <p class="text-gray-600 mt-2">En la sección inferior se puede pulsar el botón "Realizar sorteo" para generar los resultados del sorteo y obtener a los participantes seleccionados.</p>
</div>

templates/secciones/instrucciones_4.html
<div class="container mx-auto py-8 w-2/3">
    <div class="flex justify-center">
        <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">Parte 4 del sorteo</h1>
    </div>
    <p class="text-gray-600 mt-2">El sorteo ya ha sido realizado y los participantes seleccionados pueden consultarse en las secciones apropiadas de el menú lateral.</p>
    <p class="text-gray-600 mt-2">En la sección inferior se pueden descargar dos archivos: un archivo CSV en formato similar al utilizado inicialmente, pero con información añadida sobre el resultado final del sorteo, y un informe en formato PDF con la información relevante del sorteo.</p>
</div>

templates/secciones/instrucciones_error_varios_csvs.html
<div class="container mx-auto py-8 w-2/3">
    <div class="flex justify-center">
        <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">Parte 2 del sorteo - AVISO</h1>
    </div>
    <p class="text-gray-600 mt-2">Hay más de un CSV, algo que no debería ocurrir y que posiblemente se deba al resultado de pruebas durante el desarrollo.</p>
</div>

templates/secciones/instrucciones_tras_cargado_datos.html
<div class="container mx-auto py-8 w-2/3">
    <div class="flex justify-center">
        <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">Cargado de datos COMPLETADO</h1>
    </div>
    <p class="text-gray-600 mt-2">El sistema ha procesado el CSV y ha generado los participantes{% if total_participantes %}, habiendo un total de {{ total_participantes }} participantes{% endif %}. Pueden comprobarse los datos en las secciones apropiadas en el menú lateral.</p>
    <p class="text-gray-600 mt-2">Para continuar, haz click en la sección "Sorteo" presente en el menú lateral. En ella se puede pulsar el botón "Realizar sorteo" para generar los resultados del sorteo y obtener a los participantes seleccionados.</p>
</div>

templates/secciones/tabla_participantes.html
<div class="container mx-auto py-4">
    <div class="overflow-x-auto">
        <table class="min-w-full bg-white">
            <thead>
                <tr class="bg-rojoosasuna text-white uppercase text-xs leading-tight">
                    <th class="py-2 px-4 text-left {% if not_millar %}hidden{% endif %}" data-column="millar">
                        Millar
                        <span class="sort-icons">
                            <span class="sort-asc hover:text-gray-700 cursor-pointer">&#9660;</span>
                            <span class="sort-desc hover:text-gray-700 cursor-pointer">&#9650;</span>
                        </span>
                    </th>
                    <th class="py-2 px-4 text-left" data-column="posicion_millar">
                        Posición Millar
                        <span class="sort-icons">
                            <span class="sort-asc hover:text-gray-700 cursor-pointer">&#9660;</span>
                            <span class="sort-desc hover:text-gray-700 cursor-pointer">&#9650;</span>
                        </span>
                    </th>
                    <th class="py-2 px-4 text-left" data-column="numero_socio">
                        Nº Socio
                        <span class="sort-icons">
                            <span class="sort-asc hover:text-gray-700 cursor-pointer">&#9660;</span>
                            <span class="sort-desc hover:text-gray-700 cursor-pointer">&#9650;</span>
                        </span>
                    </th>
                    <th class="py-2 px-4 text-left" data-column="nombre_y_apellidos">
                        Nombre y Apellidos
                        <span class="sort-icons">
                            <span class="sort-asc hover:text-gray-700 cursor-pointer">&#9660;</span>
                            <span class="sort-desc hover:text-gray-700 cursor-pointer">&#9650;</span>
                        </span>
                    </th>
                    <th class="py-2 px-4 text-left" data-column="ganador">
                        Seleccionado
                        <span class="sort-icons">
                            <span class="sort-asc hover:text-gray-700 cursor-pointer">&#9660;</span>
                            <span class="sort-desc hover:text-gray-700 cursor-pointer">&#9650;</span>
                        </span>
                    </th>
                    <th class="py-2 px-4 text-left" data-column="reserva_tercera_fase">
                        Reserva
                        <span class="sort-icons">
                            <span class="sort-asc hover:text-gray-700 cursor-pointer">&#9660;</span>
                            <span class="sort-desc hover:text-gray-700 cursor-pointer">&#9650;</span>
                        </span>
                    </th>
                    <!-- <th class="py-2 px-4 text-left" data-column="fase_ganada">
                        Fase ganada
                        <span class="sort-icons">
                            <span class="sort-asc hover:text-gray-700 cursor-pointer">&#9660;</span>
                            <span class="sort-desc hover:text-gray-700 cursor-pointer">&#9650;</span>
                        </span>
                    </th>
                    <th class="py-2 px-4 text-left" data-column="fase_ganada">
                        Millar seleccionado
                        <span class="sort-icons">
                            <span class="sort-asc hover:text-gray-700 cursor-pointer">&#9660;</span>
                            <span class="sort-desc hover:text-gray-700 cursor-pointer">&#9650;</span>
                        </span>
                    </th> -->
                </tr>
            </thead>
            <tbody class="text-gray-600 border-gray-500 text-xs font-light">
                {% for participante in participantes %}
                <tr class="border-b border-gray-500 bg-gray-100 hover:bg-gray-200 {% if participante.ganador %}font-semibold {% endif %}">
                    <td class="py-2 px-4 text-left whitespace-nowrap {% if not_millar %}hidden{% endif %}" data-column="millar">{{ participante.millar }}</td>
                    <td class="py-2 px-4 text-left" data-column="posicion_millar">{{ participante.posicion_millar }}</td>
                    <td class="py-2 px-4 text-left" data-column="numero_socio">{{ participante.numero_socio }}</td>
                    <td class="py-2 px-4 text-left" data-column="nombre_y_apellidos">{{ participante.nombre_y_apellidos }}</td>
                    <td class="py-2 px-4 text-left" data-column="ganador">
                        {% if participante.ganador is None %}
                            No se ha sorteado
                        {% elif participante.ganador %}
                            <span class="text-red-600 font-bold">Sí</span>
                        {% else %}
                            No
                        {% endif %}
                    </td>
                    <td class="py-2 px-4 text-left" data-column="reserva_tercera_fase">
                        {% if participante.reserva_tercera_fase is None %}
                            No se ha sorteado
                        {% elif participante.reserva_tercera_fase %}
                            Sí
                        {% else %}
                            No
                        {% endif %}
                    </td>
                    <!-- <td class="py-2 px-4 text-left" data-column="fase_ganada">
                        <span class="text-red-600 font-bold text-lg">{{ participante.fase_ganada }}</span>
                    </td>
                    <td class="py-2 px-4 text-left" data-column="fase_ganada">
                        {% if participante.millar_ganador is None %}
                            No se ha sorteado
                        {% elif participante.millar_ganador %}
                            <span class="text-red-600 font-bold text-lg">{{ participante.millar_ganador }}</span>
                        {% else %}
                            No
                        {% endif %}
                    </td> -->
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
    document.querySelectorAll('.sort-asc, .sort-desc').forEach(function(icon) {
        icon.addEventListener('click', function() {
            var th = icon.closest('th');
            var table = th.closest('table');
            var column = th.getAttribute('data-column');
            var order = icon.classList.contains('sort-asc') ? 'asc' : 'desc';
            sortTable(table, column, order);
        });
    });

    function sortTable(table, column, order) {
        var tbody = table.querySelector('tbody');
        var rows = Array.from(tbody.querySelectorAll('tr'));

        rows.sort(function(a, b) {
            var aText = a.querySelector('td[data-column="' + column + '"]').textContent.trim();
            var bText = b.querySelector('td[data-column="' + column + '"]').textContent.trim();

            if (!isNaN(aText) && !isNaN(bText)) {
                aText = parseFloat(aText);
                bText = parseFloat(bText);
            }

            if (order === 'asc') {
                return aText > bText ? 1 : -1;
            } else {
                return aText < bText ? 1 : -1;
            }
        });

        rows.forEach(function(row) {
            tbody.appendChild(row);
        });
    }
</script>