herramienta_sorteo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('subir_csv/', views.subir_csv, name='subir_csv'),
    path('resumen_de_datos/', views.resumen_de_datos, name='resumen_de_datos'),
    path('procesar_participantes_csv/', views.procesar_participantes_csv, name='procesar_participantes_csv'),
    path('participantes/', views.participantes, name='participantes'),
    path('millares/', views.millares, name='millares'),
    path('ayuda/', views.ayuda, name='ayuda'),
    path('herramientas/', views.herramientas, name='herramientas'),
    path('reiniciar_sistema/', views.reiniciar_sistema, name='reiniciar_sistema'),
    path('resetear_ganadores/', views.resetear_ganadores, name='resetear_ganadores'),
    path('realizar_sorteo/', views.realizar_sorteo, name='realizar_sorteo'),
    path('ver_sorteo/', views.ver_sorteo, name='ver_sorteo'),
    path('descargar_csv_sorteo/', views.descargar_csv_sorteo, name='descargar_csv_sorteo'),
    path('descargar_pdf_sorteo/', views.descargar_pdf_sorteo, name='descargar_pdf_sorteo'),
]

templates/ayuda.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto py-8 w-2/3">
    <div class="flex justify-center">
        <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">Ayuda</h1>
    </div>
    <div class="mt-6 p-4 bg-gray-100 rounded-md">
        <h2 class="text-xl font-semibold mb-4">¿Cómo funciona el sorteo?</h2>
        <p class="text-lg text-gray-700 mb-4">
            El sorteo se divide en 3 fases y se rige por los estatutos del Club Atlético Osasuna. Los participantes se dividen en millares.
        </p>
        <p class="text-lg text-gray-700 mb-4">
            Se comienza aplicando la fase 1 a cada uno de los millares secuencialmente. Si el número de participantes del millar es igual o menor a 33, no se hace nada en esta fase. Si tiene más de 33 participantes, se realiza el sorteo aleatorio seleccionando 33 participantes y marcando al resto de participantes no seleccionados como participantes de reserva.
        </p>
        <p class="text-lg text-gray-700 mb-4">
            Se aplica la fase 2 también secuencialmente a cada millar. No hace nada excepto en los millares que tienen exactamente 33 participantes. En este caso, selecciona a los 33 participantes y no realiza más acciones, al no quedar participantes de reserva.
        </p>
        <p class="text-lg text-gray-700 mb-4">
            Se aplica la fase 3, también secuencialmente a cada millar. Solo aplica cambios en millares con menos de 33 participantes. En estos casos, selecciona a los participantes de dicho millar, calcula el número de participantes seleccionados restantes hasta 33 y selecciona a ese número de participantes de reserva previamente obtenido de los participantes no seleccionados de la primera fase.
        </p>
    </div>
    <div class="mt-6 p-4 bg-gray-100 rounded-md">
        <h2 class="text-xl font-semibold mb-2">¿Cómo se suben los datos de los participantes?</h2>
        <p class="text-lg text-gray-700">
            Los datos de los participantes deben subirse en formato CSV (comma separated values) con 4 columnas:
        </p>
        <ul class="list-disc list-inside ml-4 mt-2 text-lg text-gray-700">
            <li>Millar</li>
            <li>Orden</li>
            <li>Nº Socio</li>
            <li>Nombre</li>
        </ul>
        <p class="mt-4 text-lg text-gray-700">Ejemplo de archivo CSV:</p>
        <div class="bg-gray-200 p-4 rounded-md mt-2">
            <pre class="whitespace-pre-wrap">Millar,Orden,Nº Socio,Nombre
1,1,421,Javier García García
5,1,953,Sandra García García
7,5,1827,Daniel García García
9,7,2469,Isabel García García</pre>
        </div>
        <p class="text-lg text-gray-700">
            Guardar el archivo con extensión .csv y subirlo en la página principal.
        </p>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org@1.6.1"></script>
    <link href="{% static 'css/tailwind.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'escudo.png' %}">
    <title>Sorteo Osasuna</title>
</head>
<body class="bg-white">
    <div class="flex">
        <!-- Navbar -->
        <div class="fixed top-0 left-0 h-full">
            {% include 'navbar.html' %}
        </div>
        <!-- Main Content -->
        <div class="flex-1 p-8 ml-64">
            {% if messages %}
                <div class="flex items-center justify-center my-4">
                    {% include 'messages.html' %}
                </div>
            {% endif %}
            <main class="py-12">
                {% block content %}
                {% endblock %}
            </main>
        </div>
    </div>
</body>
</html>

templates/herramientas.html
{% extends "base.html" %}

{% block content %}
    <div class="container mx-auto p-4 text-center">
        <div class="flex justify-center">
            <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">Herramientas</h1>
        </div>
        <div class="content-section flex flex-col space-y-4 items-center">
            <div class="bg-gray-100 rounded-lg p-4 shadow-md w-1/2">
                <p class="text-sm text-gray-700 mb-2">Este botón resetea el sistema completamente. Elimina participantes, resultados y el/los CSV(s) subidos y generados.</p>
                <a href="{% url 'main_app:reiniciar_sistema' %}" class="inline-block bg-rojoosasuna hover:bg-red-700 text-white font-bold py-4 px-6 mt-2 rounded-full shadow-lg text-xl transition duration-300 ease-in-out transform hover:scale-105">
                    Reiniciar sistema
                </a>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-md w-1/2">
                <p class="text-sm text-gray-700 mb-2">Este botón resetea el sorteo, sin eliminar el CSV inicial ni los participantes generados, únicamente los resultados (incluyendo CSV y PDF finales).</p>
                <a href="{% url 'main_app:resetear_ganadores' %}" class="inline-block bg-rojoosasuna hover:bg-red-700 text-white font-bold py-4 px-6 mt-2 rounded-full shadow-lg text-xl transition duration-300 ease-in-out transform hover:scale-105">
                    Resetear ganadores
                </a>
            </div>
            <!-- <div class="bg-gray-100 rounded-lg p-4 shadow-md w-1/3">
                <p class="text-sm text-gray-700 mb-2">Description for Link 3.</p>
                <a href="#" class="inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-4 px-6 mt-2 rounded-full shadow-lg text-xl transition duration-300 ease-in-out transform hover:scale-105">
                    Link 3
                </a>
            </div>
            <div class="bg-gray-100 rounded-lg p-4 shadow-md w-1/3">
                <p class="text-sm text-gray-700 mb-2">Description for Link 4.</p>
                <a href="#" class="inline-block bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-4 px-6 mt-2 rounded-full shadow-lg text-xl transition duration-300 ease-in-out transform hover:scale-105">
                    Link 4
                </a>
            </div> -->
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    {% include 'secciones/index_presorteo.html' %}
{% endblock %}

templates/messages.html
<div class="container mx-auto p-4 w-1/2">
    {% for message in messages %}
        <div id="message_item_{{ message.id }}" class="relative mb-4 p-4 rounded-lg shadow-md bg-gray-100 border border-gray-400 text-gray-700">
            <span class="font-bold">
                {% if message.tags == 'error' %} Error:
                {% elif message.tags == 'warning' %} Aviso:
                {% elif message.tags == 'success' %} Éxito:
                {% elif message.tags == 'info' %} Información:
                {% else %} Mensaje:
                {% endif %}
            </span> 
            {{ message }}
            <button id="message_close_{{ message.id }}" class="absolute top-0 right-0 mt-2 mr-2 text-gray-500 hover:text-gray-700 text-xl border border-gray-300 rounded-full">
                &times;
            </button>
        </div>
    {% endfor %}
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('[id^="message_close_"]').forEach(function(button) {
            button.addEventListener('click', function() {
                var messageId = this.id.replace('message_close_', 'message_item_');
                var messageElement = document.getElementById(messageId);
                if (messageElement) {
                    messageElement.classList.add('hidden');
                }
            });
        });
    });
</script>

templates/millares.html
{% extends "base.html" %}

{% block content %}
    {% if total_participantes == 0 %}
        {% include 'secciones/aviso.html' with titulo='Los millares no están disponibles todavía' texto='Para generar los millares de participantes en los que se divide el sorteo, sube el archivo CSV en formato adecuado desde la pantalla de inicio. Después, procésalo siguiendo las instrucciones y podrás ver los millares de los participantes en esta sección.' %}
    {% else %}
        {% include 'secciones/contenido_millares.html' %}
    {% endif %}
{% endblock %}

templates/navbar.html
{% load static %}
<div class="bg-rojoosasuna text-white w-64 h-full pl-8 p-4 osasuna-camisetas-font">
    <img src="{% static 'logo.png' %}" alt="Logo" class="my-16">
    <nav class="space-y-4">
        <a href="{% url 'main_app:index' %}" class="block text-xl text-gray-300 hover:text-white transform hover:scale-105 transition-transform duration-200">Carga de datos</a>
        <hr class="border-gray-500 w-3/4 mx-auto">
        <a href="{% url 'main_app:resumen_de_datos' %}" class="block text-xl text-gray-300 hover:text-white transform hover:scale-105 transition-transform duration-200">Resumen de datos</a>
        <hr class="border-gray-500 w-3/4 mx-auto">
        <a href="{% url 'main_app:participantes' %}" class="block text-xl text-gray-300 hover:text-white transform hover:scale-105 transition-transform duration-200">Participantes</a>
        <hr class="border-gray-500 w-3/4 mx-auto">
        <a href="{% url 'main_app:millares' %}" class="block text-xl text-gray-300 hover:text-white transform hover:scale-105 transition-transform duration-200">Millares</a>
        <hr class="border-gray-500 w-3/4 mx-auto">
        <a href="{% url 'main_app:ver_sorteo' %}" class="block text-xl text-gray-300 hover:text-white transform hover:scale-105 transition-transform duration-200">Sorteo</a>
        <hr class="border-gray-500 w-3/4 mx-auto">
        <a href="{% url 'admin:index' %}" class="block text-xl text-gray-300 hover:text-white transform hover:scale-105 transition-transform duration-200">Admin</a>
        <hr class="border-gray-500 w-3/4 mx-auto">
        <a href="{% url 'main_app:herramientas' %}" class="block text-xl text-gray-300 hover:text-white transform hover:scale-105 transition-transform duration-200">Herramientas</a>
        <hr class="border-gray-500 w-3/4 mx-auto">
        <a href="{% url 'main_app:ayuda' %}" class="block text-xl text-gray-300 hover:text-white transform hover:scale-105 transition-transform duration-200">Ayuda</a>
    </nav>
</div>

templates/notas.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto py-8 w-2/3">
    <h1 class="text-3xl font-bold mb-6">Notas de desarrollo</h1>
    <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-2xl font-semibold mb-4">Temas a tratar</h2>
        <ul class="list-disc list-inside space-y-4">
            <li class="text-gray-700">
                <span class="font-bold">Tema 1:</span> Texto largo describiendo algo que puede ser importante y relevante para el desarrollo.
            </li>
            <li class="text-gray-700">
                <span class="font-bold">Tema 2:</span> Descripción breve.
            </li>
        </ul>
    </div>
</div>
{% endblock %}

templates/participantes.html
{% extends "base.html" %}

{% block content %}
    {% if total_participantes == 0 %}
        {% include 'secciones/aviso.html' with titulo='No hay participantes' texto='Para generar los participantes del sorteo, sube el archivo CSV en formato adecuado desde la pantalla de inicio. Después, procésalo siguiendo las instrucciones y podrás ver los participantes en esta sección.' %}
    {% else %}
        {% include 'secciones/tabla_participantes.html' %}
    {% endif %}
{% endblock %}

templates/resumen_de_datos.html
{% extends "base.html" %}

{% block content %}
    {% if total_participantes == 0 %}
        {% include 'secciones/aviso.html' with titulo='No hay participantes' texto='Para ver el resumen de datos de los participantes del sorteo, sube el archivo CSV en formato adecuado desde la pantalla de inicio. Después, procésalo siguiendo las instrucciones y podrás ver el resumen de los datos de los participantes en esta sección.' %}
    {% else %}
    <div class="container mx-auto py-8 w-2/3">
        <div class="flex justify-center">
            <h1 class="text-5xl font-bold p-2 mb-6 osasuna-camisetas-font text-left">Resumen de Datos</h1>
        </div>
        <h2 class="text-3xl font-semibold mb-4">Participantes</h2>
        <ul class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for millar in sorteo.millares %}
                <li class="text-gray-700 bg-gray-100 p-4 rounded-lg shadow">
                    <span class="font-bold">Millar {{ forloop.counter }}:</span> {{ millar.cuenta_participantes }} participantes
                </li>
            {% endfor %}
            <li class="text-gray-700 text-lg bg-gray-200 p-4 rounded-lg shadow">
                <span class="font-bold underline">Total:</span> {{ total_participantes }} participantes
            </li>
        </ul>
    </div>
    {% endif %}
{% endblock %}

templates/ver_sorteo.html
{% extends "base.html" %}

{% block content %}
    {% if sorteo_finalizado %}
        {% include 'secciones/index_resultado_sorteo.html' %}
    {% else %}
        {% if total_participantes == 0 %}
            {% include 'secciones/aviso.html' with titulo='No hay participantes' texto='Para generar los participantes del sorteo, sube el archivo CSV en formato adecuado desde la pantalla de inicio. Después, procésalo siguiendo las instrucciones y podrás ver los participantes en esta sección.' %}
        {% else %}
            {% include 'secciones/index_generar_sorteo.html' %}
        {% endif %}
    {% endif %}
{% endblock %}